/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "settings.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;

///// main func prototyping /////
void init(void);
void mode_set(void);
//void exit(void);

////////// variables //////////
unsigned int gear_mode; //Parking(0)-Rear(1)-Driving(2)
unsigned int prev_mode;

//for interrupt variable
int red_t_switch;
int blue_t_switch;

void init_P(void);
void init_R(void);
void init_D(void);

void timer_P(void);
void timer_R(void);
void timer_D(void);

void buzzer_P(void);
void photo_D(void);

void ultra_R(void);

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    init();

    while(1)
    {
        mode_set();

        if(prev_mode != gear_mode){
            switch(gear_mode){
                case 0: init_P(); break;
                case 1: init_R(); break;
                case 2: init_D(); break;
            } prev_mode = gear_mode;
        }

        if(gear_mode == 1) buzzer_P();
        else if(gear_mode == 2) photo_D();
    }

    // exit();
    return (1);
}

// Timing Interrupt - Parking
__interrupt( 0x0A ) __vector_table( 0 )
void CCU60_T12_ISR(void)
{
    if(gear_mode == 0) timer_P();        // Parking
    else if (gear_mode == 1) timer_R();
    else if (gear_mode == 2) timer_D();

    //else if (gear_mode == 1) timer_R();  // Rear
    //else if (gear_mode == 2) timer_D();  // Driving
}

__interrupt( 0x0B ) __vector_table( 0 )
void ERU0_ISR(void)
{
    ultra_R();
}


///interrupt for switch_ D Mode
__interrupt(0x0C) __vector_table(0)
void ERU0_ISR2(void)
{
    if(red_t_switch)           // Toggle LED RED
    {
        red_t_switch = 0;
    }
    else{
        red_t_switch = 1;
        blue_t_switch = 0;
    }
}

__interrupt(0x0D) __vector_table(0)
void ERU0_ISR3(void)
{
    if(blue_t_switch)           // Toggle LED RED
    {
        blue_t_switch = 0;
    }
    else{
        blue_t_switch = 1;
        red_t_switch = 0;
    }
}
