help:
	@echo "make all"
	@echo "make clean"
	@echo "---------------------------------"
	@echo "------------^^^^-----------------"


all:
	gcc -c main.c
	gcc -c foo.c
	
	gcc -o main main.o foo.o


clean:
	rm *.o main


